companies:
  Woolworths:
    aliases:
      - Woolies
      - WWS
      - Woolworths Australia
  Hanshow:
    aliases:
      - Hanshow Technology
      - Hanshow Australia

projects:
  Woolworths N70 Robot Test Unit:
    aliases:
      - N70 robot
      - large robot test unit
      - robot test unit
      - Woolworths robot pilot
      - Woolworths N70

people:
  Ben:
    aliases:
      - Ben from Woolworths
  Travis:
    aliases:
      - Travis from Woolworths

